### PR TITLE
Dev/issue 11064 remove project specifics

### PR DESCRIPTION
**Pull request by jrwdunham**
If you call `./runtests` against an AM stable/1.6 deploy, the relevant tests should pass.

### CODE REVIEW

**Comment by joel-simpson** [comment]
I ran ./runtests using Chrome (from my Mac) against Archivematica 1.6 (running on a digital ocean VM). One scenario (in one feature) failed with the following error. I'm not sure if this is an issue with the tests, my Archivematca deployment, or something to do with my laptop.
(I have uploaded results of all tests in the following text file - error starts on line 67.

[runtests.sh_error_May8.txt](https://github.com/artefactual-labs/archivematica-acceptance-tests/files/985014/runtests.sh_error_May8.txt)

**Comment by jrwdunham** [comment]
@joel-simpson I'll look into this and see if I get the same result. It looks like the METS file XML is being truncated and then lxml is choking on trying to parse it.

**Comment by joel-simpson** [comment]
@jrwdunham some further info that might help: I did a fresh install on my other Mac, and ran behave --tags=premis-events --tags=standard --no-skipped on a new 
On this dev branch, I got the same error as I showed above (or the first few lines are all the same; 
the error messages get slightly different later on).  
I then ran the exact same command on the master branch, and it all passed succesfully.  Which suggests there is something different in your dev branch causing issues. 
[premis-events_error_May_10.txt](https://github.com/artefactual-labs/archivematica-acceptance-tests/files/991461/premis-events_error_May_10.txt)
[premis-events_pass_master_may10.txt](https://github.com/artefactual-labs/archivematica-acceptance-tests/files/991462/premis-events_pass_master_may10.txt)

**Comment by jrwdunham** [comment]
@joel-simpson that's weird and I don't know how to explain why master would be passing but dev/issue-11064-remove-project-specifics would be failing: I can't see any changes in the code that should really change how the tests are run. 

It could be that the tests are failing sporadically/randomly because of Selenium/browser/driver incompatibilities. I see you're using Mac Chrome 58. I have had more consistent results with Firefox 47 and Chrome 57.

Both of your error outputs are indicating that parsing the METS file is failing either because Selenium has to wait too long before it can get the METS XML or the XML is truncated. See below.

- may 8 error:

    - Then in the METS file there are/is 11 PREMIS event(s) of type unpacking
    - archivematicaselenium.py, line 467, in get_mets::

        >>> return etree.fromstring(mets.encode('utf8'))
        lxml.etree.XMLSyntaxError: Premature end of data in tag originalName
            line 170, line 170, column 107

- may 10 error:

    - Then in the METS file there are/is 7 PREMIS event(s) of type ingestion                                                                                                                                                                                                                                     # features/steps/steps.py:330 313.958s
    - archivematicaselenium.py, line 464, in get_mets::

        >>> mets = self.driver.page_source
        selenium.common.exceptions.TimeoutException: Message: timeout

I have been successful in getting the tests on this dev/issue-11064-remove-project-specifics branch to pass against a AM stable/1.6.x deploy using Xvfb, Firefox v. 47.0.1 and the command::

    ./runtests.sh \
        -D am_url=http://192.168.168.16/ \
        -D ss_url=http://192.168.16.16:8000/ \
        -D driver_name=Firefox

    2 features passed, 0 failed, 5 skipped
    6 scenarios passed, 0 failed, 16 skipped
    82 steps passed, 0 failed, 281 skipped, 0 undefined
    Took 25m27.917s

**Comment by jrwdunham** [comment]
@joel-simpson since jsimpson and I both got the tests to pass with this branch, I'm going to commit this PR. Then you can rebase your JiscRDSS:dev/issue-11064-remove-project-specifics so that it doesn't include the same changes in this PR.

**Pull request merged**
