### PR TITLE
Add feature: performance gains without stdout

### LINKED ISSUE #32: Enhancement: create feature file comparing performance with/without stdout/err in db
Create a feature file that describes anticipated behaviour when the same transfer is run through two different Archivematica deployments which are identical except that one has client scripts that pass stdout/stderr back to MCPServer to be stored in the database and the other simply discards such stdout/stderr. The feature file should express an expectation that the stdout/stderr-discarding system should have significant relative performance gains.

### PR DESCRIPTION
**Pull request by jrwdunham**
This commit introduces feature file performance-stdout-no-write.feature, which
first creates an AIP using a version of Archivematica where the MCP client
passes its client script output streams (stdout and stderr) to the MCP server
for ultimate storage in the database. The timing duration of each client
script run in the course of building that AIP is queried from the
database and saved to disk. The feature then modifies the Archivematica
instance so that the MCP client no longer passes output streams to the
server, and it creates a new AIP, and saves information on micro-service
execution time to disk. Finally, it asserts that the micro-services took
less time in the second case than in the first.

This feature is essentially the executable documentation of a performance
experiment against Archivematica. The current finding is that removing
output streams results in a 6% reduction in task execution time.

Warning: it is a known bug that executing this feature will stall at the
second instance of the `And standard AIP-creation decisions are made`
step.

Fixes #32.

### CODE REVIEW

**Comment by sevein** [comment]
@jrwdunham do we need to add the Columbia label so it's back to waffle?

**Comment by jrwdunham** [comment]
Performance Increase Without Output Streams Feature File
==============================================================================

Warning: this feature file should only be run in development. It requires a
docker-compose-based Archivematica deploy. The test itself must be able to
alter the deployment, i.e., check the source code out to a new revision and
restart Archivematica. This feature was developed against an AM deploy
created using https://github.com/artefactual-labs/am and Archivematica at
branch dev/1.8.x (be8fdee61851e180cd4dbab0af54fad3f5766066). The test itself
checks out a locally accessible dev/1.8.x-without-logs branch at the hash
provided under `commit_without_outputs` below and restarts Archivematica using
docker-compose.

To run the test, deploy Archivematica locally using 
https://github.com/artefactual-labs/am::

    $ git clone https://github.com/artefactual-labs/am
    $ cd am/compose
    $ git submodule update --init --recursive
    $ cd ../src/archivematica
    $ git checkout be8fdee61851e180cd4dbab0af54fad3f5766066
    $ cd ../../compose
    $ make create-volumes
    $ docker-compose up -d --build
    $ make bootstrap
    $ make restart-am-services

Then run the following `behave` command, after replacing the
`docker_compose_path` and `am_src_path` userdata options with the appropriate
values for your development system::

    behave \
        --tags=performance-no-stdout \
        --no-skipped \
        --no-capture \
        -D driver_name=Firefox \
        -D am_url=http://127.0.0.1:62080/ \
        -D am_password=test \
        -D home=archivematica \
        -D am_version=1.7 \
        -D docker_compose_path=/abs/path/to/am/compose \
        -D am_src_path=/abs/path/to/am/src/archivematica

Results
==============================================================================

Results from 3 Runs of this test
------------------------------------------------------------------------------

1. Total runtime for without output tasks: 412.99 seconds
   Total runtime for with output tasks:    439.22 seconds

2. Total runtime for without output tasks: 394.35 seconds
   Total runtime for with output tasks:    434.23 seconds

3. Total runtime for without output tasks: 429.57 seconds
   Total runtime for with output tasks:    444.76 seconds

Analysis
------------------------------------------------------------------------------

Average runtime for without output tasks: 412.30 seconds
Average runtime for with output tasks:    439.40 seconds
Average time reduction of 6%

**Comment by jrwdunham** [comment]
@jhs @scollazo @sevein you might find this interesting (or appalling)

**Comment by scollazo** [comment]
I think that your numbers might be affected by behave, because when there are transfers in the dashboard, it takes a bit more of time to being load. 

Can you run a query similar to this in order to check if results are consistent?
<pre>
select exec,avg(TIMEDIFF(endTime , startTime)) as avg_script_execution_time, max(TIMEDIFF(endTime , startTime)) as max_script_execution_time, min(TIMEDIFF(endTime,startTime)) as min_script_execution_time ,count(*) as total_script_executions ,sum(TIMEDIFF(endTime , startTime)) as total_script_exec_time, max(TIMEDIFF(startTime, createdTime)) as max_script_queue_wait from Tasks  group by exec order by exec;
</pre>

**Pull request merged**
